update to release based on v3.9.0 (#106)
* update to release based on v3.9.0

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* fixes test-app error Checking for block from: tests/app/expected-output/tools/show.txt
Error: Block from tests/app/expected-output/tools/show.txt not found in /tmp/cli-tools-show-output.log.
Error: Process completed with exit code 1.

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* nvidia-visible-devices all vs void

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

* update for v3.9.0 GA

Signed-off-by: Wenqi Li <wenqil@nvidia.com>

---------

Signed-off-by: Wenqi Li <wenqil@nvidia.com>